XorHub/XorHub/Controllers/AssignmentController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using XorHub.Models;
using System.Data.Entity.Validation;

namespace XorHub.Controllers
{
    public class AssignmentController : Controller
    {
        // GET: Assignment
        public ActionResult StudentResponse(int id)
        {
            if (Session["username"] == null || Session["usertype"] == null)
            {
                return RedirectToRoute(new
                {
                    controller = "Index",
                    action = "Index",
                    id = 1
                });
            }

            AssignmentSolutionModel asModel = new AssignmentSolutionModel();
            asModel.Solution = new Solution() { Stat = "P"};

            using (XorHubEntities db = new XorHubEntities())
            {
                List<SelectListItem> list = new List<SelectListItem>();
                foreach (var item in db.Batches)
                {
                    list.Add(new SelectListItem { Text = item.Name, Value = item.BatchId.ToString() });
                }

                asModel.Assignment = db.Assignments.Where(a => a.AssignmentId == id).FirstOrDefault();

                var sol = db.Solutions.Where(s => s.AssignmentId == id && s.Stat.Equals("A")).FirstOrDefault();
                if (sol != null)
                {
                    asModel.Solution = sol;
                }

                ViewData["BatchList"] = list;
            }
            ViewBag.filePath = "~/Database/Questions/"+ id + ".pdf";
            ViewBag.state = false;

            return View(asModel);
        }

        public ActionResult ViewResponse(int id)
        {
            if (Session["username"] == null || Session["usertype"] == null)
            {
                return RedirectToRoute(new
                {
                    controller = "Index",
                    action = "Index",
                    id = 1
                });
            }

            AssignmentSolutionModel asModel = new AssignmentSolutionModel();
            List<Solution> listSolutions = new List<Solution>();
            using (XorHubEntities db = new XorHubEntities())
            {
                asModel.Assignment = db.Assignments.Where(a => a.AssignmentId == id).FirstOrDefault();
                listSolutions = db.Solutions.Where(s => s.AssignmentId == id && s.Stat.Equals("A")).ToList();
            }

            ViewBag.solutions = listSolutions;

            return View(asModel);
        }

        public ActionResult TeacherResponse(int id)
        {
            if (Session["username"] == null || Session["usertype"] == null)
            {
                return RedirectToRoute(new
                {
                    controller = "Index",
                    action = "Index",
                    id = 1
                });
            }

            AssignmentSolutionModel asModel = new AssignmentSolutionModel();
            List<Solution> listSolutions = new List<Solution>();
            using (XorHubEntities db = new XorHubEntities())
            {
                asModel.Assignment = db.Assignments.Where(a=>a.AssignmentId == id).FirstOrDefault();
                listSolutions = db.Solutions.Where(s => s.AssignmentId == id).ToList();
            }

            ViewBag.filePath = "~/Database/Questions/" + asModel.Assignment.AssignmentId + ".pdf";
            ViewBag.solutions = listSolutions;

            return View("TeacherResponse", asModel);
        }

        [HttpPost]
        public ActionResult PostQuestion(HttpPostedFileBase QueFile, Assignment assignment)
        {
            assignment.PostedDate = DateTime.Now;
            
            if (assignment.Deadline < assignment.PostedDate)
            {
                return RedirectToAction("Teacher", "Home", new { id = 4}); 
            }

            assignment.TeacherName = Session["username"].ToString();

            if (!Directory.Exists(Server.MapPath("~/Database/Questions/")))
            {
                Directory.CreateDirectory(Server.MapPath("~/Database/Questions/"));
            }

            using (XorHubEntities db = new XorHubEntities())
            {
                db.Assignments.Add(assignment);
                db.SaveChanges();
            }

            try
            {
                QueFile.SaveAs(Path.Combine(Server.MapPath("~/Database/Questions"), assignment.AssignmentId.ToString() + ".pdf"));
            }
            catch (Exception ex)
            {
                return RedirectToAction("Teacher", "Home", new { id = 1 });
            }



            ViewBag.Message = "Question Successfully uploaded!";

            return RedirectToAction("Teacher", "Home");
        }

        [HttpPost]
        public ActionResult Submit(HttpPostedFileBase solutionDoc, AssignmentSolutionModel asModel)
        {
            if(asModel.Assignment.Deadline < DateTime.Now)
            {
                ViewBag.Message = "Deadline crossed! Cannot Submit Solution";
                ViewBag.filePath = "~/Database/Questions/" + asModel.Assignment.AssignmentId + ".pdf";
                return View("StudentResponse", asModel);
            }

            if (!Directory.Exists(Server.MapPath("~/Database/Solutions/" + Session["username"].ToString())))
            {
                Directory.CreateDirectory(Server.MapPath("~/Database/Solutions/" + Session["username"].ToString()));
            }

            try
            {
                solutionDoc.SaveAs(Path.Combine(Server.MapPath("~/Database/Solutions/" + Session["username"].ToString() + "/"), asModel.Assignment.AssignmentId + ".pdf"));
            }
            catch (Exception ex)
            {
                ViewBag.Message = "Please Select File!";
                ViewBag.filePath = "~/Database/Questions/" + asModel.Assignment.AssignmentId + ".pdf";
                return View("StudentResponse", asModel);
            }


            Solution soln = new Solution() {
                AssignmentId = asModel.Assignment.AssignmentId,
                Username = Session["username"].ToString(),
                Stat = "P",
                UploadedOn = DateTime.Now,
                Document = asModel.Assignment.AssignmentId + ".pdf",
                Comment = ""
            };
            using (XorHubEntities db = new XorHubEntities())
            {
                try
                {
                    string userName = Session["username"].ToString();
                    if (db.Solutions.Any(s => s.Username.Equals(userName) && s.AssignmentId == asModel.Assignment.AssignmentId))
                    {
                        var tmp = db.Solutions.Where(s => s.Username.Equals(userName) && s.AssignmentId == asModel.Assignment.AssignmentId).FirstOrDefault();
                        tmp = soln;
                        db.SaveChanges();
                    }
                    else
                    {
                        db.Solutions.Add(soln);
                        db.SaveChanges();
                    }
                }
                catch (DbEntityValidationException e)
                {

                }
            }

            return RedirectToRoute(new
            {
                Controller = "Home",
                Action = "Student",
                id = 3
            }
            );
        }

        public new ActionResult Response(int id)
        {
            if (Session["username"] == null || Session["usertype"] == null)
            {
                return RedirectToRoute(new
                {
                    controller = "Index",
                    action = "Index",
                    id = 1
                });
            }

            Solution sol = new Solution();
            using (XorHubEntities db = new XorHubEntities())
            {
                sol = db.Solutions.Where(s => s.SolutionId == id).FirstOrDefault();
                sol.Assignment = db.Assignments.Where(a => a.AssignmentId == sol.AssignmentId).FirstOrDefault();
            }

            if (Session["usertype"].ToString().Equals("T"))
                ViewBag.IsDisplay = true;
            else
                ViewBag.IsDisplay = false;

            return View(sol);
        }


        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Approve(Solution sol)
        {
            using (XorHubEntities db = new XorHubEntities())
            {
                var soln = db.Solutions.Where(s => s.SolutionId == sol.SolutionId).FirstOrDefault();
                soln.Stat = "A";
                soln.Comment = sol.Comment;
                db.SaveChanges();
            }
            return RedirectToAction("TeacherResponse", new { id = sol.AssignmentId });
        }

        [HttpParamAction]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Reject(Solution sol)
        {
            using (XorHubEntities db = new XorHubEntities())
            {
                var soln = db.Solutions.Where(s => s.SolutionId == sol.SolutionId).FirstOrDefault();
                soln.Stat = "R";
                soln.Comment = sol.Comment; db.SaveChanges();
            }

            return RedirectToAction("TeacherResponse", new { id = sol.AssignmentId });
        }
    }
}

XorHub/XorHub/Views/Assignment/Response.cshtml
@model Solution

@{
    ViewBag.Title = "Response";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />

<div class="container">
    <div class="panel panel-body">
        <h5 style="font-size: 16px"><strong>Title </strong>: @Html.Label(Model.Assignment.Title) </h5>
    </div>

    <div class="panel panel-body">
        <h5 style="font-size: 16px"><strong>Response </strong>: </h5>
        <embed src=@Url.Content(String.Format("~/Database/Solutions/{0}/{1}.pdf", Model.Username, Model.Assignment.AssignmentId)) width="100%" height="400" alt="pdf" pluginspage="http://www.adobe.com/products/acrobat/readstep2.html">
    </div>



    @if (ViewBag.IsDisplay)
    {
        <div class="panel panel-body">
            @using (Html.BeginForm("Action", "Assignment", FormMethod.Post))
            {
            @Html.HiddenFor(s => s.SolutionId)
            @Html.HiddenFor(s => s.AssignmentId)

            <h5 style="font-size: 16px"><strong> Comment </strong>: </h5>
            @Html.TextAreaFor(s => s.Comment, new {  style = "width: 100", placeholder = "Enter Comment Here.." })
            <br />
            <input class="btn btn-primary" type="submit" name="Approve" value="Approve" />
            <input class="btn btn-primary" type="submit" name="Reject" value="Reject" />
            }
        </div>
    }
    else
    {
        if (Model.Comment != null)
        {
            <div class="panel panel-body">
                <h5 style="font-size: 16px"><strong>Comment </strong>: </h5>
                @Model.Comment
            </div>
        }
    }


</div>

XorHub/XorHub/Views/Assignment/StudentResponse.cshtml
@model XorHub.Models.AssignmentSolutionModel

@{
    ViewBag.Title = "StudentResponse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /> <br />

<div class="container">
    <div class="panel panel-body">
        <h5 style="font-size: 16px"><strong>Title </strong>: @Model.Assignment.Title </h5>
        <h5 style="font-size: 16px"><strong>Batch </strong>: @Model.Assignment.BatchId </h5>
    </div>

    <div class="panel panel-body">
        <embed src=@Url.Content(String.Format("{0}", ViewBag.filePath)) width="100%" height="400" alt="pdf" pluginspage="http://www.adobe.com/products/acrobat/readstep2.html" >
    </div>

    <div class="panel panel-body">
        @if(ViewBag.Message != null)
        {
            <div class="alert alert-dismissible alert-warning">
                @ViewBag.Message
            </div>
        }

        @using (Html.BeginForm("submit", "Assignment", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(u => u.Assignment.AssignmentId)
            @Html.HiddenFor(a => a.Assignment.BatchId)
            @Html.HiddenFor(t => t.Assignment.Title)
            @Html.HiddenFor(t => t.Assignment.Deadline)
            <div class="response">
                <h5>Solution</h5>
                <input class="form-control" type="file" id="solutionDoc" name="solutionDoc" accept=".pdf" />
                <br />
                <input class="btn btn-primary" type="submit" name="Submit" value="Submit"
                        onsubmit= "return checkFile()" />
                
                @* Allow student to view other solutions if its solution is approved *@
                
                @if (Model.Solution.Stat.Equals("A"))
                {
                    <a href=@Url.Content(String.Format("/Assignment/ViewResponse/{0}", Model.Assignment.AssignmentId))> View Responses </a>
                }

            </div>
        }
    </div>
</div>

<script type="text/javascript">
    function checkFile() {
        var file = document.getElementById('solutionDoc').value;

        if (file == null) {
            alert("Upload File First!");
            return false;
        }
        else {
            return true;
        }
    }
</script>

XorHub/XorHub/Views/Assignment/TeacherResponse.cshtml
@model XorHub.Models.AssignmentSolutionModel

@{
    ViewBag.Title = "TeacherResponse";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />

<div class="container">
    <div class="panel panel-body">
        <h5 style="font-size: 16px"><strong>Title </strong>: @Model.Assignment.Title </h5>
        <h5 style="font-size: 16px"><strong>Batch </strong>: @Model.Assignment.BatchId </h5>
    </div>
  
    <div class="panel panel-body">
        <embed src=@Url.Content(String.Format("{0}", ViewBag.filePath)) width="100%" height="400" alt="pdf" pluginspage="http://www.adobe.com/products/acrobat/readstep2.html">
    </div>

    <div class="panel panel-body">
        @using (Html.BeginForm("submit", "Assignment", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(u => u.Assignment.AssignmentId)

            <div>
                <h4>Responses</h4>
                @foreach (Solution sol in (IEnumerable<Solution>)ViewBag.solutions)
                {
                    <div class="row response">
                        <a href=@Url.Content(string.Format("/Assignment/Response/{0}", sol.SolutionId))>
                            <div class="col-md-4">
                                <h5><strong>  @sol.Username</strong> </h5>
                            </div>
                            <div class="col-md-2">
                                <small> @sol.UploadedOn</small>
                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-md-4">
                                Status :
                                @switch (sol.Stat)
                                {
                                    case "P":
                                        @Html.Label("Pending")
                                        break;

                                    case "A":
                                        @Html.Label("Approved")
                                        break;

                                    case "R":
                                        @Html.Label("Rejected")
                                        break;

                                    default:
                                        break;
                                }
                            </div>
                        </a>
                    </div>
                }
            </div>
        }
    </div>

</div>

XorHub/XorHub/Views/Assignment/ViewResponse.cshtml
@model XorHub.Models.AssignmentSolutionModel
@{
    ViewBag.Title = "ViewResponses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />

<div class="container">
    <div class="panel panel-body">
        <h5 style="font-size: 16px"><strong>Title </strong>: @Model.Assignment.Title </h5>
        <h5 style="font-size: 16px"><strong>Batch </strong>: @Model.Assignment.BatchId </h5>
    </div>
 
    <div class="panel panel-body">
        @using (Html.BeginForm("submit", "Assignment", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(u => u.Assignment.AssignmentId)

            <div>
                <h5>Responses</h5>
                @foreach (Solution sol in (IEnumerable<Solution>)ViewBag.solutions)
                {
                    <div class="panel panel-body row">

                        <div class="col-md-4">
                            <a href=@Url.Content(String.Format("/Assignment/Response/{0}", sol.SolutionId))>
                                <h4><strong> @sol.Username</strong> </h4>
                            </a>
                        </div>
                        <div class="col-md-2">
                            <small> @sol.UploadedOn</small>
                        </div>
                        <div class="col-md-2"></div>
                        <div class="col-md-4"></div>

                    </div>
                }
            </div>
        }
    </div>

</div>